### ISSUE TITLE
Beta (1.50) does not compile

### ISSUE THREAD

**Issue by msrd0** [msrd0/alpine-rust#1]
```
2021-01-10T23:07:58.402855813Z    Compiling installer v0.0.0 (/home/alpine-rust/package/src/rustc-beta-src/src/tools/rust-installer)
2021-01-10T23:08:12.776891610Z     Finished release [optimized] target(s) in 25.16s
2021-01-10T23:08:12.796497611Z       < ToolBuild { compiler: Compiler { stage: 0, host: TargetSelection { triple: "x86_64-alpine-linux-musl", file: None } }, target: TargetSelection { triple: "x86_64-alpine-linux-musl", file: None }, tool: "fabricate", path: "src/tools/rust-installer", mode: ToolBootstrap, is_optional_tool: false, source_type: Submodule, extra_features: [] }
2021-01-10T23:08:12.796548641Z     < RustInstaller { compiler: Compiler { stage: 0, host: TargetSelection { triple: "x86_64-alpine-linux-musl", file: None } }, target: TargetSelection { triple: "x86_64-alpine-linux-musl", file: None } }
2021-01-10T23:08:12.796603810Z     c Assemble { target_compiler: Compiler { stage: 0, host: TargetSelection { triple: "x86_64-alpine-linux-musl", file: None } } }
2021-01-10T23:08:12.796629170Z Dist rust-std-1.50.0-x86_64-alpine-linux-musl
2021-01-10T23:08:12.796673060Z running: "/home/alpine-rust/package/src/rustc-beta-src/build/x86_64-alpine-linux-musl/stage0-tools-bin/fabricate" "generate" "--image-dir" "/home/alpine-rust/package/src/rustc-beta-src/build/tmp/tarball/x86_64-alpine-linux-musl/image" "--component-name=rust-std-x86_64-alpine-linux-musl" "--rel-manifest-dir=rustlib" "--legacy-manifest-dirs=rustlib,cargo" "--product-name=Rust" "--success-message=rust-std installed." "--package-name=rust-std-1.50.0-x86_64-alpine-linux-musl" "--non-installed-overlay" "/home/alpine-rust/package/src/rustc-beta-src/build/tmp/tarball/x86_64-alpine-linux-musl/overlay" "--output-dir" "/home/alpine-rust/package/src/rustc-beta-src/build/dist" "--work-dir" "/home/alpine-rust/package/src/rustc-beta-src/build/tmp/tarball/x86_64-alpine-linux-musl"
2021-01-10T23:08:32.207138068Z  finished in 19.410 seconds
2021-01-10T23:08:32.207180568Z   < Std { compiler: Compiler { stage: 2, host: TargetSelection { triple: "x86_64-alpine-linux-musl", file: None } }, target: TargetSelection { triple: "x86_64-alpine-linux-musl", file: None } }
2021-01-10T23:08:32.207219838Z Install std stage2 (Some(TargetSelection { triple: "x86_64-alpine-linux-musl", file: None }))
2021-01-10T23:08:32.207429816Z running: "sh" "/home/alpine-rust/package/src/rustc-beta-src/build/tmp/dist/rust-std-1.50.0-x86_64-alpine-linux-musl/install.sh" "--prefix=/home/alpine-rust/package/pkg/rust-beta/usr" "--sysconfdir=/home/alpine-rust/package/pkg/rust-beta/etc" "--datadir=/home/alpine-rust/package/pkg/rust-beta/usr/share" "--docdir=/home/alpine-rust/package/pkg/rust-beta/usr/share/doc/rust" "--bindir=/home/alpine-rust/package/pkg/rust-beta/usr/bin" "--libdir=/home/alpine-rust/package/pkg/rust-beta/usr/lib" "--mandir=/home/alpine-rust/package/pkg/rust-beta/usr/share/man" "--disable-ldconfig"
2021-01-10T23:08:32.208135052Z sh: can't open '/home/alpine-rust/package/src/rustc-beta-src/build/tmp/dist/rust-std-1.50.0-x86_64-alpine-linux-musl/install.sh': No such file or directory
2021-01-10T23:08:32.208219652Z 
2021-01-10T23:08:32.208240481Z 
2021-01-10T23:08:32.208251321Z command did not execute successfully: "sh" "/home/alpine-rust/package/src/rustc-beta-src/build/tmp/dist/rust-std-1.50.0-x86_64-alpine-linux-musl/install.sh" "--prefix=/home/alpine-rust/package/pkg/rust-beta/usr" "--sysconfdir=/home/alpine-rust/package/pkg/rust-beta/etc" "--datadir=/home/alpine-rust/package/pkg/rust-beta/usr/share" "--docdir=/home/alpine-rust/package/pkg/rust-beta/usr/share/doc/rust" "--bindir=/home/alpine-rust/package/pkg/rust-beta/usr/bin" "--libdir=/home/alpine-rust/package/pkg/rust-beta/usr/lib" "--mandir=/home/alpine-rust/package/pkg/rust-beta/usr/share/man" "--disable-ldconfig"
2021-01-10T23:08:32.208279221Z expected success, got: exit code: 2
2021-01-10T23:08:32.208286951Z 
2021-01-10T23:08:32.208291531Z 
2021-01-10T23:08:32.210627877Z Traceback (most recent call last):
2021-01-10T23:08:32.210653057Z   File "./x.py", line 11, in <module>
2021-01-10T23:08:32.210662217Z     bootstrap.main()
2021-01-10T23:08:32.210670277Z   File "/home/alpine-rust/package/src/rustc-beta-src/src/bootstrap/bootstrap.py", line 1088, in main
2021-01-10T23:08:32.210677907Z     bootstrap(help_triggered)
2021-01-10T23:08:32.210684757Z   File "/home/alpine-rust/package/src/rustc-beta-src/src/bootstrap/bootstrap.py", line 1074, in bootstrap
2021-01-10T23:08:32.210691427Z     run(args, env=env, verbose=build.verbose)
2021-01-10T23:08:32.210697416Z   File "/home/alpine-rust/package/src/rustc-beta-src/src/bootstrap/bootstrap.py", line 153, in run
2021-01-10T23:08:32.210704256Z     raise RuntimeError(err)
2021-01-10T23:08:32.210710526Z RuntimeError: failed to run: /home/alpine-rust/package/src/rustc-beta-src/build/bootstrap/debug/bootstrap install -v
2021-01-10T23:08:32.217785493Z >>> ERROR: rust-beta*: package failed
2021-01-10T23:08:32.218226141Z >>> ERROR: rust-beta: rootpkg failed
```

**Comment by msrd0** [comment]
`build/dist/rust-std-1.50.0-x86_64-alpine-linux-musl.tar.gz` contains a file called `rust-std-1.50.0-x86_64-alpine-linux-musl/install.sh`, but `build/tmp/` does not contain a `dist` folder. Maybe archive extraction didn't work?
